### ISSUE TITLE
Motofit GUI 'To Code' doesn't update transform for Objective()

### ISSUE THREAD

**Issue by nolahlm** [refnx/refnx#309]
Creating a model with the Jupyter GUI is very intuitive and the "to code" button is great for model reproducibility; however, if you update the GUI plot type in Options --> Plot Type to logY and then use the "to code" button the Objective class is not fed the transformation type selected in the GUI.

**Comment by andyfaff** [comment]
thank you for submitting your first issue @nolahlm, and contributing towards refnx advancement. #310 fixes the issue.
