### ISSUE TITLE
CurveFitter.fit() only optimises nll

### ISSUE THREAD

**Issue by arm61** [refnx/refnx#318]
As it stands the [`CurveFitter.fit()`](https://github.com/refnx/refnx/blob/ee4227275c0d2d2f414a09e5f478ee220cb9a687/refnx/analysis/curvefitter.py#L538) function will only minimise the negative log-likelihood (or residuals for least-squares). 

This means that for systems such as the [`LipidLeaflet`](https://github.com/refnx/refnx/blob/ee4227275c0d2d2f414a09e5f478ee220cb9a687/refnx/reflect/_lipid.py#L10) class, the [`logp()`](https://github.com/refnx/refnx/blob/ee4227275c0d2d2f414a09e5f478ee220cb9a687/refnx/reflect/_lipid.py#L270) function has no effect on the initial fitting. 

Would it be relevant to allow the `CurveFitter.fit()` function to optimise the negaive log posterior in addition to the negative log likelihood?

**Comment by andyfaff** [comment]
If all the probability distributions for `logp` are uniform (majority of cases) then there is no difference to maximising the posterior compared to the likelihood, it's just a constant addition. They would start to differ when the priors aren't uniform. The `differential_evolution` and `LBFGS` algorithms are good for optimising parameter values within those bounds.
The main problem with minimising negative logposterior is that if there are some impossible regions (`logp == -np.inf`) then the optimizers may start to fall over. I think differential evolution would cope, but LBFGSB would fail.

**Comment by arm61** [comment]
Interesting, I will test the method that I have implemented with a couple of different optimisation methods

**Comment by andyfaff** [comment]
https://wiseodd.github.io/techblog/2017/01/01/mle-vs-map/

**Comment by arm61** [comment]
I am wanting to move towards a Gaussian prior implementation (which I am aware would require some special case `bounds` being implemented). However, in the meantime it is mostly about getting the `-np.inf` to have an effect.

**Comment by andyfaff** [comment]
You can use any scipy stats distribution with the `PDF` class, enabling a
Gaussian prior. This obviously works for the MCMC sampling, being encoded
in the log posterior. It should therefore also work for minimising negative
log posterior. I reckon it should be possible to use differential evolution
for that.

**Comment by andyfaff** [comment]
The PDF class is [here](https://github.com/refnx/refnx/blob/master/refnx/analysis/bounds.py#L72).

**Comment by arm61** [comment]
Resolved in #319
