### ISSUE TITLE
Test for nlpost

### ISSUE THREAD

**Issue by arm61** [refnx/refnx#322]
need to write a test for the objective.nlpost function

**Comment by arm61** [comment]
Happy to take care of this tomorrow am

**Comment by andyfaff** [comment]
I added a smoke test in #321. However, it's not doing what I'd expect to
happen. I expected the max likelihood and max posterior to be the same if
the bounds are uniform because the log prior just contributes a constant
term to the log posterior. I'm going to look into that further tomorrow.
