### ISSUE TITLE
progress bar for fitting?

### ISSUE THREAD

**Issue by jfkcooper** [refnx/refnx#422]
I have been trying to work out how to view or implement a progress bar for the fit, or at least some verbose output. Am using jupyter notebooks, but I don't think that this matters????

**Comment by andyfaff** [comment]
There's a progress bar for fitting and sampling in the GUI.

In Jupyter notebooks there's a progress bar for the sampling (if you have tqdm installed), but no progress bar for the fitting. This could be implemented at the refnx level, but it'd also be possible for the user to provide a callback function via kwd arguments that are then passed on to the minimizer. This callback could increment it's own progress bar. I would do that by creating a callback class:

```
class Callback():
    def __init__(self):
        # create/initialise progress bar

    def __call__(self, x):
        # increment progress bar

callback = Callback()
fitter.fit(callback=callback)
```

**Comment by andyfaff** [comment]
What exactly would you want to see in a progress bar/progess update?
With sampling you know how far through the entire thing you are. Sometimes it's not possible with least squares to know when the end is, so you could display:

- number of iterations, maxiter, time
- chi2

The difference is that the minimisation will typically end before the end of the progress bar.

**Comment by jfkcooper** [comment]
This is very true, I guess just some level of verbose output, chi2 would be conventional and informative I think. I was looking to see if tqmd could estimate the progress, but wasn't getting so far as am not familiar with it (and only saw it as you seem to have used it for the other progress bars)

**Comment by andyfaff** [comment]
For personal use I'd probably create a callback and print chi2 every few iterations.

**Comment by andyfaff** [comment]
I suppose it's not a bad idea to add something along these lines. I just need to find a keyword that doesn't clash with the minimizers. I think `verbose` might work, and it's the same as used for sample.
I still don't know what to display in the progress bar.

```
from tqdm import tqdm

class Callback():
    def __init__(self, maxiter):
        self.maxiter = maxiter
        self._bar = tqdm(total=self.maxiter)
        self._it = 0

    def __call__(self, x, convergence):
        self._it += 1
        self._bar.update(1)
        self._bar.refresh()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self._bar.close()

fitter = CurveFitter(objective)

with Callback(1000) as c:
    res = fitter.fit('differential_evolution', callback=c)
```

**Comment by andyfaff** [comment]
It's not a simple thing to add, because it would have to wrap any callback that the user provides as well.
