### ISSUE TITLE
Saving and loading models from code

### ISSUE THREAD

**Issue by gfreychet** [refnx/refnx#436]
I ran into issues when trying to save and load models using Motofit. I can save the model fine but when I try to load it, I got an error saying:
AttributeError: 'Stack' object has no attribute 'thick'

My model is composed of a stack component. I added my model file saved.
[test_highchi1.txt](https://github.com/refnx/refnx/files/4542390/test_highchi1.txt)

**Comment by andyfaff** [comment]
Thank you for this report. Are you using the GUI? Can you send me an experiment file so that I can examine it?

**Comment by andyfaff** [comment]
I've tried opening the file in the latest release of refnx, using the standalone GUI, and the model seems to open ok. All the parameters are given funny names though, like `0.028145`.

- Did you create the file using the GUI, or via Jupyter notebook (please send through whatever you used to create it)?
- what version of refnx did you use to save the file? what version are you using to open the file?

**Comment by gfreychet** [comment]
Thank you for the quick answer.!

I am running the code outside of  the gui, in jupyter notebook.
My refnx version is 0.1.12.

**Comment by andyfaff** [comment]
Do you mind sending me the notebook then? If you don't want to post here, you could email me a link to a private gist.

**Comment by andyfaff** [comment]
My email is andyfaff@gmail.com
