### ISSUE TITLE
Using specified peak_pos (position, FWHM) in ReductionOptions is applied to both reflected and direct beam

### ISSUE THREAD

**Issue by ohcpaull** [refnx/refnx#497]
Would be best if this was only applied to the reflected beam for situations where you want to test reductions with a specified position and FWHM that has been determined by the manual beam finder. Are there any situations where you need to specify the position and FWHM for the direct beam?

**Comment by andyfaff** [comment]
At the moment it's only possible to specify a single `peak_pos` for both the reflected and direct beams, because it's the same `ReductionOptions` used for both.
I'll have a think about how to achieve that.

**Comment by andyfaff** [comment]
I've changed the code so that when reducing to a reflectometry file `peak_pos` from the ReductionOptions is only applied to the reflected beam.
