### ISSUE TITLE
Can't use non-Slab object as fronting or backing

### ISSUE THREAD

**Issue by Armatron44** [refnx/refnx#529]
Hi,

I’d like to use a `MixedSlab` component as the last component in a `Structure`. However, I’ve run into the exception raised in the `slabs` method of the `Structure` class that checks both the fronting and backing components are slabs. From a quick test, where I've removed this check along with the similar check in the `sld_profile` method, I can still fit data and the SLD profile can be correctly calculated. Is it be possible to allow components other than slabs in the fronting and backing positions, or will it cause issues elsewhere?

Thanks,

Sandy

**Comment by andyfaff** [comment]
One of the reasons that check was introduced is because some `Component` need to know what components are before and after them. This would make them unsuitable as backing materials.

A further reason is that the backing slab is also typically the material that is used to solvate the rest of the structure:

>  If no solvent is specified then the SLD of the solvent is assumed to be the SLD of `Structure[-1].slabs()[-1]` (after any possible slab order reversal).

This means that if `Structure.solvent` is not specified then `vfsolv` for the backing slab should be 0 and not allowed to vary during a fit (the thickness of the backing slab is also ignored and should be fixed during a fit).

Is there a specific reason why you'd like to have use a MixedSlab as the backing medium? Is it not just easier to construct a `Slab` out of a single `SLD` object?

**Comment by Armatron44** [comment]
The reason I'd like to use a `MixedSlab` as the backing component is that I'm trying to model a known volumetric mixture of h- and d-solvent. While the SLD of the h-solvent is known and fixed, the SLD of d-solvent is not known but is expected to be around the SLD at 95–100 % d content. Fortunately, I have a d-contrast so the d-solvent SLD can be determined via a fit. Ideally, I would like to globally fit both contrasts, where the d-solvent SLD is a varying parameter that also determines the SLD of the solvent mixture through a volume fraction function. However, as far as I know, you cannot specify a SLD object in terms of a function of another varying parameter (be that another SLD object or just a standard parameter) without the SLD object adopting a fixed value throughout the fit - is that correct?

As part of my quick check earlier, I did check if a Slab that was solvated by the MixedSlab worked, and it appeared to function well.

**Comment by andyfaff** [comment]
What you're asking to do with the MixedSlab seems eminently feasible, I'll look into modifying the code to allow it. You could use the modified code in a Jupyter Notebook, but I don't think I'd change the standalone GUI for this, it would be a bit too fiddly.

I can upgrade your knowledge level, you can apply constraints in refnx of the kind of thing you were thinking of. Try out the following:

```
from refnx.reflect import Structure, Slab, SLD
from refnx.analysis import Parameter

# parameter to hold the real part of the deuterated SLD
deut_par = Parameter(6.36, name="real part of the deuterated SLD")
deut_solvent = SLD(deut_par)
print(deut_solvent, deut_solvent.real is deut_par)

# h-solvent
h2o_solvent = SLD(-0.56)
print(h2o_solvent.real)

# I assume that you know what the volume fraction ratios of the two are.
# Here let's say they're 60:40 D/H
ms_val = 0.6 * deut_par + 0.4 * h2o_solvent.real
print(ms_val)

# we should be able to construct an SLD objecct with ms_val, but there's a tweak I should be doing here.
mixed_solvent = SLD(-1000.0)
mixed_solvent.real = ms_val
print(mixed_solvent)

# test by changing SLD of deut solvent
deut_par.value = 5.0
print(deut_solvent)
print(mixed_solvent)
```

You could use this `mixed_solvent` object as the last slab in constructing a `Structure` in a global fit.

**Comment by andyfaff** [comment]
See also #530 and #531

**Comment by andyfaff** [comment]
@Armatron44, I've just made a 0.1.18 release that allows `MixedSlab` to be used as a backing medium. It will also allow `SLD` objects to be constructed with the constraints specified in the previous post:

```
from refnx.reflect import Slab, SLD
from refnx.analysis import Parameter

deut_par = Parameter(6.36, name="real part of the deuterated SLD")
deut_solvent = SLD(deut_par)

h2o_solvent = SLD(-0.56)

ms_val = 0.6 * deut_par + 0.4 * h2o_solvent.real
mixed_solvent = SLD(ms_val)
```
