### ISSUE TITLE
Inability to reduce older PNR data as the spin channels were not automatically identified

### ISSUE THREAD

**Issue by dcortie** [refnx/refnx#582]
The script below gives a minimal example below 
This fails to run because the algorithm to identify what the spin state fails
The issue can be fixed by modifying the if statement below in platypusnexus.py
Line ~778 if channel.spin_state is  _spin_channels[sc] 

```
from refnx.reduce import PolarisedReduce, SpinSet
from refnx.reduce import PolarisationEfficiency
import matplotlib.pyplot as plt

directory = "c:\Test\PNR_files"

spinset_rb1 = SpinSet(
    down_down = "PLP0016430.nx.hdf",
    up_up = "PLP0016431.nx.hdf",
    data_folder = directory
)


spinset_db1 = SpinSet(
    down_down = "PLP0016426.nx.hdf",
    up_up = "PLP0016427.nx.hdf",
    data_folder = directory
)

polreduce = PolarisedReduce(spinset_db1)
polreduce.reduce(spinset_rb1, save=True, scale=1.5, lo_wavelength=2.3, hi_wavelength=12, rebin_percent=2)



plt.errorbar(
    polreduce.reducers["uu"].x[0], 
    polreduce.reducers["uu"].y[0] ,
    polreduce.reducers["uu"].y_err[0],
    label="++"
)

plt.errorbar(
    polreduce.reducers["dd"].x[0], 
    polreduce.reducers["dd"].y[0], 
    polreduce.reducers["dd"].y_err[0],
    label="--"
)


plt.legend()
plt.yscale("log")
```

**Comment by andyfaff** [comment]
```
import h5py
from refnx.reduce import PlatypusNexus

with h5py.File('PLP0016427.nx.hdf', 'r') as f:
    cat = PolarisedCatalogue(f)
    pn = PlatypusNexus(f)
cat.pol_flip_current, cat.anal_flip_current, cat.cat['z_trans'], pn.spin_state, cat.mode, 
```

gives:
```
(5.0, 0.0, -200.00061, <SpinChannel.UP_DOWN: (1, 0)>, 'POL')
```

- `PlatypusNexus` sees 16427 as an UD file. 
- When `spinset_db1` is constructed it checks that the `up_up` channel argument has a matching spin state. In this case it doesn't, because it thinks 16427 is an UD file. Thus, spinset_db1 has an `up_up` attribute of None, and the reduction doesn't work.

The key is why does `PlatypusNexus` classify 16427 as UD? It does so because the `pol_flip_current = 5.0` and `anal_flip_current = 0.0`. However, we see that the analyser isn't in (`z_trans = -200.0`), and that `mode = POL`. Thus we're not in a spin analysed setup.
What should refnx classify this file as, UP_UP?

**Comment by andyfaff** [comment]
Probably fixed by  #584

**Comment by andyfaff** [comment]
With #584 applied the reduction example above proceeds without fail. The two spin states look very similar though.

**Comment by dcortie** [comment]
Thanks, glad we got to bottom of this! Yes, the spin-states look similar, because the samples are essentially non-magnetic in this case. Old Igor Pro reduction confirms this point. If you want to see splitting, reduce 16428, 16429. 

As to how to classify the file in the refnx code... 
Normally when people designate a reflectometry channel like R_{++} with two subscripts, or alternatively as up-up or down-down, the implicit meaning is the analyser was in.  If the analyser was not in, normally we'd write this as R_{+} or R_{-} indicating that the outgoing spin channel was not analysed. Will have to think exactly how to present this in the code itself.
