### ISSUE TITLE
R increase at the beginning of the curve

### ISSUE THREAD

**Issue by hetian-chen** [refnx/refnx#616]
For the measured data, R increases at the beginning of the curve (Q is from 0 to 0.05 Å ^(-1)). While for the fitting, R remains constant or decreases. Can someone tell me the reason?

**Comment by hetian-chen** [comment]
![This is an image](file:///C:/Users/chenhetian/Desktop/fig.png)

**Comment by andyfaff** [comment]
I can't see that image unfortunately. If the reflectivity is increasing below the critical edge then it might be due to footprint. Are you measuring on an angular dispersive instrument?

**Comment by hetian-chen** [comment]
Thanks very much for your reply! This explanation indeed makes sense! Is it possible to consider the dispersal? Or we fit the XRR curve after the critical angle.

**Comment by andyfaff** [comment]
refnx currently doesn't do this kind of correction during a fit. However, it is possible to apply footprint corrections to the original dataset, then fit the amended data.

**Comment by hetian-chen** [comment]
May I know how to conduct the footprint corrections? It would be very nice if there is any relevant book or website.

**Comment by andyfaff** [comment]
Do you know the beam profile of the X-ray beam? If so, then one can use `refnx.util.beamfrac` to estimate the proportion of a Gaussian beam intercepted by the sample for different angles. You then divide through the data by that proportion. Once all the beam is intercepted by the sample the fraction is 1.

**Comment by hetian-chen** [comment]
Thank you very much! It really helps a lot. I think I can get the beam profile by scanning without a sample.
