### ISSUE TITLE
refnx doesn't accept pathlib.Path objects as filenames

### ISSUE THREAD

**Issue by llimeht** [refnx/refnx#641]
Using [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) objects makes dealing with filesystem objects much simpler and less verbose, for example eliminating many of the `os.path.join` dances. The [multicontrast example](https://refnx.readthedocs.io/en/latest/reflectometry_global.html) could, for instance, become:

```python
from pathlib import Path
datadir = Path(refnx.__file__).parent / "analysis" / "test"
e361 = ReflectDataset(datadir / "e361r.txt")
```

Support for `Path` objects instead of `str` objects is now quite good across most of stdlib and so it would be nice for refnx to support that too. Given that refnx is already testing types, then adding `isinstance(data, pathlib.PurePath)` would work; `possibly_open_file` looks like it will already accept `Path` objects.

**Comment by andyfaff** [comment]
Well on way with #642

**Comment by andyfaff** [comment]
I think we're done with Paths now. If you find any more let me know.
